FROM rackspacedot/python37
CMD ["bash"]

# Install Node.js 8 and npm 5
RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash -
RUN apt-get -y install nodejs
RUN apt install wget

RUN mkdir /workspace
WORKDIR /workspace

RUN mkdir /workspace/model

COPY requirements.txt .
RUN pip install -r ./requirements.txt
RUN python -m spacy download en_core_web_md

COPY package.json .
RUN npm install
RUN apt-get install -y supervisor

COPY model /workspace/model

COPY server.py .
COPY server.js .
COPY modeling-cpu.py ./modeling.py
COPY infer-cpu.py ./infer.py
COPY infer_utils.py .
COPY iq.py .
COPY texts ./texts
EXPOSE 80

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord"]
