openapi: 3.0.1
info:
  title: QnA-BOT
  description: QnA bot powered by CoQA + BERT built in Pytorch.
  contact:
    email: hanjeong@comcom.ai
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: https://qnabot-cpu.gkswjdzz.endpoint.ainize.ai
tags:
- name: BOT
  description: talk with bot
paths:
  /chat:
    get:
      tags:
      - BOT
      summary: You can use parasite bot..
      parameters:
      - name: bot_id
        in: query
        description: write name of your bot
        required: true
        schema:
          type: string
          enum:
            - parasite_bongjunho
            - ain_wp
            - demo
        example: parasite_all
      - name: question
        in: query
        description: question
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  okay:
                    type: string
                  question:
                    type: string
        405:
          description: Invalid input
          content: {}